# Generated by Django 4.0.4 on 2022-04-26 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1024, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=1024, verbose_name='Sobrenome')),
                ('pontuacao', models.FloatField(default=0, verbose_name='Pontuação')),
                ('tipo', models.CharField(choices=[('P', 'Predador'), ('R', 'Realizador'), ('S', 'Socializador'), ('E', 'Explorador')], default='P', max_length=1024, verbose_name='Tipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
