# Generated by Django 4.0.4 on 2022-05-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_professoresturma'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
    ]
