# Generated by Django 4.0.4 on 2022-05-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_turma_ativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='semestre',
            field=models.CharField(default=1010.0, max_length=1024, verbose_name='Semestre'),
            preserve_default=False,
        ),
    ]
