# Generated by Django 4.0.4 on 2022-05-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_turma_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='pontuacao',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Pontuação'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='tipo',
            field=models.CharField(blank=True, choices=[('P', 'Predador'), ('R', 'Realizador'), ('S', 'Socializador'), ('E', 'Explorador')], default='P', max_length=1024, null=True, verbose_name='Tipo'),
        ),
    ]
