# Generated by Django 4.0.4 on 2022-05-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aluno_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='hash_convite',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Hash Convite'),
        ),
    ]
