# Generated by Django 4.0.4 on 2022-05-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_turma_hash_convite'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='confirmado',
            field=models.BooleanField(default=False, verbose_name='Confirmado'),
        ),
    ]
